name: Ruby

on: [push]

jobs:
  rspec:

    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: test
      BUNDLE_WITHOUT: development
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.0', '3.1', '3.2']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec
