name: Static Code Analyzers

on: [push]
jobs:
  ruby:
    name: Ruby
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: development
      BUNDLE_WITHOUT: test
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.7'
          bundler-cache: true

      - name: Run Rubocop
        uses: reviewdog/action-rubocop@v1
        with:
          rubocop_extensions: 'rubocop-rspec rubocop-sorbet'
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          fail_on_error: true
          filter_mode: nofilter

      - name: Run Sorbet
        run: bundle exec srb tc
